version: 2
updates:
  - package-ecosystem: github-actions
    labels: []
    directory: /
    target-branch: dev
    schedule:
      interval: weekly

  - package-ecosystem: npm
    labels: []
    directory: /
    target-branch: dev
    schedule:
      interval: weekly

  - package-ecosystem: gradle
    labels: []
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
